export interface User {
  id : number,
  nombre : string,
  username : string,
  password : string,
  registrarCat : boolean,
  registrarPro : boolean,
  editarPro : boolean,
  eliminarPro : boolean,
  exportar : boolean,
  importar : boolean,
  imprimir : boolean,
  registrar : boolean,
  editar : boolean,
  eliminar : boolean,
  crearBackup : boolean,
  restoreBackup : boolean,
  registrarVenta : boolean,
  reportes : boolean,
  ultimasVentas : boolean
}
